# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build init`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t init`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system init && \
          adduser --system -G init init

COPY dist/init init
RUN chown -R init:init .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix init --omit=dev -f install

CMD [ "node", "init" ]
